apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: shopstr.market
  namespace: istio-system
spec:
  host: "shopstr.market"
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: shopstr.market
  namespace: istio-system
spec:
  hosts:
    - shopstr.market
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
